spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: films

filePath: films.pdf
type: pdf

google:
  storage:
    credentials: ${CREDENTIALS}
    bucket: film-reports
    projectId: films-batch